kind: pipeline
name: build_arm32v7

workspace:
  base: /go
  path: filestash

clone:
  depth: 1

platform:
  os: linux
  arch: arm

steps:

- name: build_prepare
  image: debian:stable
  depends_on: [ clone ]
  commands:
  - mkdir -p ./dist/data/state/config
  - cp config/config.json ./dist/data/state/config/
  - mkdir -p ./filestash/data/state/config
  - cp config/config.json ./filestash/data/state/config/

- name: build_frontend
  image: node:12-alpine
  depends_on: [ build_prepare ]
  commands:
  - apk add make git > /dev/null
  - npm install --silent
  - make build_frontend
  - cp -R ./dist/data/public ./filestash/data/public

- name: build_backend
  image: golang:1.14-stretch
  depends_on: [ build_prepare ]
  environment:
    CGO_LDFLAGS_ALLOW: "-fopenmp"
    GO111MODULE: "on"
  commands:
  - apt-get update > /dev/null && apt-get install -y libglib2.0-dev curl make > /dev/null
  - make build_init
  - make build_backend
  - timeout 1 ./dist/filestash || true
  - cp dist/filestash filestash/
  - chmod -R o+r+w+x ./dist/data

- name: release_prepare
  image: debian:stable-slim
  depends_on: [ build_frontend, build_backend ]
  when:
    event: tag
  commands:
  - chmod -R o-r-w-x- ./filestash
  - tar -czf filestash-arm32v7-${DRONE_COMMIT_SHA:0:7}.tar.gz ./filestash

- name: release_publish
  image: plugins/github-release
  depends_on: [ release_prepare ]
  when:
    event: tag
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    files: filestash-arm32v7-${DRONE_COMMIT_SHA:0:7}.tar.gz
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
    prerelease: true

- name: release_docker
  image: plugins/docker
  depends_on: [ release_publish ]
  when:
    event: tag
  settings:
    dockerfile: ./docker/Dockerfile
    repo: tabbyjun/filestash-arm32v7
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    tags:
    - latest
    - "${DRONE_COMMIT_SHA:0:7}"
    build_args:
    - TAG=${DRONE_TAG}
